---
title: "modelcheckplot"
output: html_document
date: "2025-01-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggnewscale)
library(tidyverse)
```

## Check item level correlation and other summary reporting statistics.

```{r, include=FALSE}
df <- read.csv('../model_data/modelAndDataUnfitpn.csv') # 288 obs of 17

```

Now a chi-sq for anti-uniform fit. Need to first group by world, and do a series of 36 chisq.


```{r}
results <- df %>%
  group_by(pg_tt) %>%
  summarise(
    chi_sq_stat = chisq.test(n, p = rep(1/n(), n()))$statistic,
    p_value     = chisq.test(n, p = rep(1/n(), n()))$p.value
  ) %>%
  mutate(
    p_adj = p.adjust(p_value, method = "bonferroni")
  )

print(results)

print(min(results$chi_sq_stat)) # 50.5
print(max(results$p_adj)) # 4e-7

```


# Now Actual

```{r}
df$Actual[is.na(df$Actual)] <- FALSE

res <- df %>% group_by(Actual) %>% summarise(n=sum(n)) # 1972 / 608 = 2580

print(chisq.test(res$n, p=c(0.5,0.5)))
```


# Unobserved

```{r}
df <- df %>% mutate(Observed = factor(!node3%in%c('Au=0','Au=1','Bu=0', 'Bu=1'), levels = c(T,F)))
# Then, like res
unobs <- df %>% group_by(Observed) %>% summarise(n=sum(n)) # 1152 / 1428 = 55.3%

print(chisq.test(unobs$n, p=c(0.5,0.5)))

```




An old one for the df as a whole: we don't use this any more:

```{r, include=FALSE}
observed <- df$n
expected <- rep((sum(df$n)/length(df$n))/sum(df$n), length(df$n))

chi_sq_result <- chisq.test(x=df$n, p = expected)
print(chi_sq_result)

```

